# Generated by Django 5.2.9 on 2026-01-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_searchhistory_travel_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='max_transfers',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Макс. пересадок'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='transport_types',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Типы транспорта'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='travel_mode',
            field=models.CharField(default='public', max_length=20, verbose_name='Тип маршрута'),
        ),
    ]
