# Generated by Django 5.2.9 on 2026-01-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_searchhistory_max_transfers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='provider',
            field=models.CharField(choices=[('2gis_route', '2GIS (Маршруты)'), ('tomtom_geocode', 'TomTom (Геокод)'), ('tomtom_route', 'TomTom (Маршруты)'), ('stub', 'Заглушка')], max_length=50),
        ),
    ]
