# Generated by Django 5.2.9 on 2025-12-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('2gis_route', '2GIS (Маршруты)'), ('tomtom_geocode', 'TomTom (Геокод)'), ('tomtom_route', 'TomTom (Маршруты)'), ('stub', 'Заглушка')], max_length=20)),
                ('request_params', models.TextField(blank=True)),
                ('response_status', models.IntegerField()),
                ('response_time_ms', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('was_cached', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CachedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('route_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Кэшированный маршрут',
                'verbose_name_plural': 'Кэшированные маршруты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_query', models.CharField(max_length=255)),
                ('end_query', models.CharField(max_length=255)),
                ('start_coords', models.CharField(blank=True, max_length=50)),
                ('end_coords', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('routes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='RouteRequest',
        ),
    ]
