# Generated by Django 5.2.9 on 2025-12-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apilog_cachedroute_searchhistory_delete_routerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='travel_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
