# Generated by Django 5.2.9 on 2025-12-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_searchhistory_travel_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='travel_mode',
            field=models.CharField(blank=True, default='car', help_text='car, pedestrian, bicycle', max_length=20, null=True, verbose_name='Тип маршрута'),
        ),
    ]
